name: Lint/test
on: [push]
jobs:
  lint:
    name: "Lint and security test the code"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run pylint in container
        run: docker run --rm -v $(pwd):/data cytopia/pylint import.py
      - name: Run security test
        run: docker run --rm -v $(pwd):/data cytopia/bandit import.py